---
title: "Keewi Code Test"
author: "Tim (Wenjie) Hu"
output: 
  github_document:
    toc: true
    toc_depth: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(googlesheets)
library(knitr)
library(stringr)
library(lubridate)
library(hms)
```

```{r}
# I tried to read data directly from google sheet, but there is a bug I couldn't fix immediately. Then I saved the data as csv on my local directory. 

# # Parameters
#   # Spreadsheet key for notes
# notes_key <- "1jiOJhqsUmHAwsgnqNSHn4m85yQL2vxhmkoZHAw2QBwQ"
# 
# # Give googlesheets permission to access spreadsheets
# gs_auth()
# 
# ## Read in notes
# notes <- 
#   gs_key(notes_key) %>%
#   gs_read(ws = "Sheet1")
```

```{r, message=FALSE, warning=FALSE}
data_file <- "/Users/timhu/Dropbox/Stanford/career/Internship/Coding Test Data - Sheet1.csv"

# read the data and remove blank columns
df_raw <- 
  read_csv(data_file, skip = 1) %>% 
  select(-c(X1, X14))

# get dataframe for device 522, 523 separately, and calculate the their sum in a new dataframe.
df_522 <- 
  df_raw %>% 
  select(`Device ID`:`Cumul kWh`)
df_523 <-
  df_raw %>% 
  select(`Device ID_1`:`Cumul kWh_1`) %>% 
  set_names(colnames(df_522))
df_sum <- 
  df_522 %>% 
  mutate(`Device ID` = "Sum",
         kWh = df_522$kWh + df_523$kWh,
         Power = df_522$Power + df_523$Power,
         `Cumul kWh` = df_522$`Cumul kWh` + df_523$`Cumul kWh`)

# concatenate above dataframes together, and get variables for the date, and time of day.
df_plot <- 
  rbind(df_522, df_523, df_sum) %>% 
  select(device = `Device ID`, cum_kWh = `Cumul kWh`, everything(), -`Excel Date`) %>% 
  mutate(date = date(time_stamp),
         daytime = as.hms(time_stamp))
```

```{r, out.width="100%"}
df_plot %>% 
  ggplot(aes(time_stamp, kWh, color = factor(device))) +
  geom_line() +
  labs(x = "Date", color = "Device ID")
```


```{r, out.width="100%"}
df_plot %>% 
  ggplot(aes(daytime, kWh, color =factor(device))) +
  geom_line() +
  facet_grid(date ~ .) +
  labs(x = "Time of Day", color = "Device ID")
  # coord_fixed(ratio=0.2)
  
```


```{r, out.width="100%"}
df_plot %>% 
  ggplot(aes(daytime, kWh, color = factor(date), linetype = factor(device))) +
  geom_line() +
  labs(linetype = "Device ID", color = "Date", x = "Time of Day")
```

```{r, out.width="100%"}
df_plot %>% 
  ggplot(aes(time_stamp, cum_kWh, color = factor(device))) +
  geom_line() +
  labs(x = "Date", color = "Device ID", y = "Cumulative kWh", title = "Cumulative kWh Consumption for One Week")
```


```{r, out.width="100%"}
df_plot %>% 
  ggplot(aes(device, kWh)) +
  geom_boxplot() +
  labs(title = "Boxplot of kWh Consumption for Differnt Devices")
```

```{r, out.width="100%"}
df_raw %>% 
  ggplot(aes(kWh, kWh_1)) +
  geom_point() +
  labs(x = "kWh(Device 522)", y = "kWh(Device 523)", 
       title = "Reading Correlation between Device 522 and 523")
```


```{r, message=FALSE, warning=FALSE, out.width="100%"}
df_raw %>% 
  filter(kWh_1 > 0.04, kWh_1 < 0.06, kWh < 0.035) %>% 
  ggplot(aes(kWh, kWh_1)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~date(time_stamp)) +
  labs(x = "kWh(Device 522)", y = "kWh(Device 523)", 
       title = "Reading Correlation between Device 522 and 523 (Outliers Removed)")
  
```

```{r}
model <- lm(kWh ~ kWh_1, data = df_raw)
summary(model)
```

